apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: quickstart.csi.k8s.io
    app.kubernetes.io/part-of: quickstart-sample-csi-driver
    app.kubernetes.io/name: csi-quickstart-plugin
    app.kubernetes.io/component: provisioner-cluster-role
  name: csi-quickstart-plugin-provisioner-cluster-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-provisioner-runner
subjects:
- kind: ServiceAccount
  name: csi-quickstart-plugin-sa
  namespace: quickstart
