apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: quickstart.csi.k8s.io
  labels:
    app.kubernetes.io/instance: quickstart.csi.k8s.io
    app.kubernetes.io/part-of: csi-driver-host-path
    app.kubernetes.io/name: quickstart.csi.k8s.io
    app.kubernetes.io/component: csi-driver
spec:
  attachRequired: false
  volumeLifecycleModes:
  - Persistent
  - Ephemeral
  podInfoOnMount: true
  fsGroupPolicy: File
