kind: Pod
apiVersion: v1
metadata:
  name: test-app
spec:
  containers:
    - name: test
      image: busybox
      volumeMounts:
      - mountPath: "/data"
        name: test-csi-volume
      command: [ "sleep", "1000000" ]
  volumes:
    - name: test-csi-volume
      csi:
        driver: quickstart.csi.k8s.io
